Implemented MonsterDao
VECTOUN/pa165project pull request #18
Opened 2017-10-26 19:07 UTC by Vojtech-Sassmann

* Implemented CRUD methods from MonsterDao in MonsterDaoImpl.
* Added JavaDoc to MonsterDao.

2017-10-26 19:20 UTC, Vojtech-Sassmann commented
Hi @balcirakpeter, @pajavyskocil, @honzogol. 
Please check this out. I think that this way should be done all Daos. If you have any notes, share them here please.

2017-10-27 11:52 UTC, balcirakpeter requested changes

2017-10-27 11:52 UTC, balcirakpeter commented on Monsters hunting persistence/src/main/java/cz/fi/muni/pa165/dao/MonsterDaoImpl.java
> +		em.persist(monster);
Add flush

2017-10-27 11:52 UTC, balcirakpeter commented on Monsters hunting persistence/src/main/java/cz/fi/muni/pa165/dao/MonsterDaoImpl.java
> +		em.remove(monster);
Add flush

2017-10-27 13:49 UTC, merged